import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";
import { GraphProvider } from "./GraphContext";
import { NavProvider } from "./NavContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-200`}>
      <NavProvider>

        <Header />
        <GraphProvider> 
          <div>{children}</div>
        </GraphProvider>
        </NavProvider>
      </body>
    </html>
  );
}
